const dotenv = require('dotenv');
const path = require('path');
const connectDB = require('./db/db');
dotenv.config({ path: path.resolve(__dirname, '../.env') });
connectDB();
const express = require('express');
const app = express();
app.use(express.json());
const cookieParser = require('cookie-parser');
app.use(cookieParser());
const userRoutes = require('./routes/user.routes');
app.use('/users', userRoutes);
module.exports = app;