const dotenv = require('dotenv');
dotenv.config();
const express = require('express');
const app = express();
app.use(express.json());
const cookieParser = require('cookie-parser');
app.use(cookieParser());
const userRoutes = require('./routes/user.routes');
app.use('/users', userRoutes);
module.exports = app;